### ISSUE TITLE
Error with laravel 4.1.29 

### ISSUE THREAD

**Issue by bsalim** [KasparBP/laravel-riak#2]
I am checking everything should be correctly installed including php-riak-stubs

PHP Fatal error:  Class 'Riak\Connection' not found in /home/vagrant/Hulaa/vendor/bach-pedersen/laravel-riak/src/BachPedersen/LaravelRiak/RiakServiceProvider.php on line 49
PHP Stack trace:
PHP   1. {main}() /home/vagrant/Hulaa/artisan:0
PHP   2. require_once() /home/vagrant/Hulaa/artisan:30
PHP   3. require() /home/vagrant/Hulaa/bootstrap/start.php:58
PHP   4. Illuminate\Foundation\ProviderRepository->load() /home/vagrant/Hulaa/vendor/laravel/framework/src/Illuminate/Foundation/start.php:210
PHP   5. Illuminate\Foundation\Application->register() /home/vagrant/Hulaa/bootstrap/compiled.php:4072
PHP   6. BachPedersen\LaravelRiakAuth\Reminder\RiakReminderProvider->register() /home/vagrant/Hulaa/bootstrap/compiled.php:525
PHP   7. BachPedersen\LaravelRiakAuth\Reminder\RiakReminderProvider->registerReminderRepository() /home/vagrant/Hulaa/vendor/bach-pedersen/laravel-riak-auth/src/BachPedersen/LaravelRiakAuth/Reminder/RiakReminderProvider.php:45
PHP   8. Illuminate\Container\Container->offsetSet() /home/vagrant/Hulaa/vendor/bach-pedersen/laravel-riak-auth/src/BachPedersen/LaravelRiakAuth/Reminder/RiakReminderProvider.php:81
PHP   9. Illuminate\Container\Container->bind() /home/vagrant/Hulaa/bootstrap/compiled.php:372
PHP  10. Illuminate\Container\Container->rebound() /home/vagrant/Hulaa/bootstrap/compiled.php:100
PHP  11. Illuminate\Foundation\Application->make() /home/vagrant/Hulaa/bootstrap/compiled.php:190
PHP  12. Illuminate\Container\Container->make() /home/vagrant/Hulaa/bootstrap/compiled.php:586
PHP  13. Illuminate\Container\Container->build() /home/vagrant/Hulaa/bootstrap/compiled.php:212
PHP  14. Illuminate\Container\Container->Illuminate\Container{closure}() /home/vagrant/Hulaa/bootstrap/compiled.php:240
PHP  15. BachPedersen\LaravelRiakAuth\Reminder\RiakReminderProvider->BachPedersen\LaravelRiakAuth\Reminder{closure}() /home/vagrant/Hulaa/bootstrap/compiled.php:125
PHP  16. Illuminate\Container\Container->offsetGet() /home/vagrant/Hulaa/bootstrap/compiled.php:84
PHP  17. Illuminate\Foundation\Application->make() /home/vagrant/Hulaa/bootstrap/compiled.php:363
PHP  18. Illuminate\Container\Container->make() /home/vagrant/Hulaa/bootstrap/compiled.php:586
PHP  19. Illuminate\Container\Container->build() /home/vagrant/Hulaa/bootstrap/compiled.php:212
PHP  20. Illuminate\Container\Container->Illuminate\Container{closure}() /home/vagrant/Hulaa/bootstrap/compiled.php:240
PHP  21. BachPedersen\LaravelRiak\RiakServiceProvider->BachPedersen\LaravelRiak{closure}() /home/vagrant/Hulaa/bootstrap/compiled.php:125
{"error":{"type":"Symfony\Component\Debug\Exception\FatalErrorException","message":"Class 'Riak\Connection' not found","file":"\/home\/vagrant\/Hulaa\/vendor\/bach-pedersen\/laravel-riak\/src\/BachPedersen\/LaravelRiak\/RiakServiceProvider.php","line":49}}vagrant@homestead

**Comment by bachpedersen** [comment]
Looks like you might need to install the php_riak php extension.
You can check with phpinfo()

**Comment by bsalim** [comment]
Ok got it fixed. Thanks for your reply
